### ISSUE TITLE
purl2dwarf: Get DWARFs from a PURL

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#260]
Create a PURL a service backed by new SCIO analysis pipelines that takes a PURL for a native binary package as an input, and returns the DWARF debug symbol compilation unit paths when available. This will specifically be worked out for Debian native binary packages.

**Comment by armijnhemel** [comment]
As a package can contain multiple binaries I guess that the result would be a list of "DWARF information per binary"?

**Comment by pombredanne** [comment]
> As a package can contain multiple binaries I guess that the result would be a list of "DWARF information per binary"?

Yes, that's per binary file

**Comment by armijnhemel** [comment]
> > As a package can contain multiple binaries I guess that the result would be a list of "DWARF information per binary"?
> 
> Yes, that's per binary file

What would this look like for a package like coreutils (with ~100 binaries)?

**Comment by pombredanne** [comment]
> What would this look like for a package like coreutils (with ~100 binaries)?

more or less like this:
```YAML
- files:
  - path: foo/bar/find
    dwarf_paths:
      - /home/joe/coreutil/includes/baz.h
      - /home/joe/coreutil/find.c
  - path: foo/bar/ls
    dwarf_paths:
      - /home/joe/coreutil/includes/baz.h
      - /home/joe/coreutil/js.c
```
